### ISSUE TITLE
Erro - Divisão por Cidade

### ISSUE THREAD

**Issue by MallonMafra** [fabioserpa/CNPJ-full#14]
Estou recebendo este erro ao separar arquivo por Cidade, alguém já teve este erro?

Traceback (most recent call last):
  File "separar_csv_por_cidade.py", line 36, in <module>
    uf_file.writelines(line)
  File "C:\Users\Alex Basto\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x8f' in position 0: character maps to <undefined>

**Comment by fabioserpa** [comment]
Esse erro ainda acontece?

**Comment by MallonMafra** [comment]
Não tentei mais, mas só consegui por estado, hoje a tarde se der tempo eu texto de novo, senão vejo amanhã, e dou retorno

 

De: fabioserpa <notifications@github.com> 
Enviada em: terça-feira, 31 de março de 2020 15:12
Para: fabioserpa/CNPJ-full <CNPJ-full@noreply.github.com>
Cc: MallonMafra <ti@mallon.com.br>; Author <author@noreply.github.com>
Assunto: Re: [fabioserpa/CNPJ-full] Erro - Divisão por Cidade (#14)

 

Esse erro ainda acontece?

**Comment by fsimoyama** [comment]
Mesmo erro pra mim hoje
UnicodeEncodeError: 'charmap' codec can't encode character '\x8f' in position 0: character maps to <undefined>

**Comment by Badlands19** [comment]
Olá, pessoal! Estou tendo erro similar. Será que tem que mudar a especificação da codificação em algum lugar? 
OS utilizado: Windows 10 64 bits

Arquivo .env: 
FILES_LOCATION=C:\Users\ivans\OneDrive\Área de Trabalho\BD\CNPJ-full-master\saida_csv

comando no cmd: 
C:\Users\ivans\OneDrive\Área de Trabalho\BD\CNPJ-full-master\extra_csv>python separar_csv_por_cidade.py

Erro:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 40: character maps to <undefined>

**Comment by fabioserpa** [comment]
O erro persistiu? Caso tenha conseguido resolver, qual foi a solução?

**Comment by cfsobral** [comment]
Prezado Fabio.

Eu nao uso sistema Windows, no caso é UNIX. O codigo rodou perfeitamente, gerou os arquivos empresas.csv, socios.csv e cnae_secundarios.csv. Porem quando fui rodar o **separar_csv_por_cidade.py** & **separar_csv_por_uf.py** emitem o seguinte erro:

File "/Volumes/Data/Master/separar_csv_por_cidade.py", line 9, in <module>
    with codecs.open(location + file,'r+','utf-8') as empresas:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Agradeço a sua ajuda porque pelo menos eu conseguir criar os csv's. Os arquivos gerados foram (mais menos) empresas(14gb), socios(2.78) e cnae(1.76). Baixei os dados ontem(14/2/21).

Obrigado.
