### ISSUE TITLE
Erro ao processar aquivo

### ISSUE THREAD

**Issue by Matheus-Thurler** [fabioserpa/CNPJ-full#28]
Teria como me ajudar a usar o código, estou tentando e o mesmo da erro ao transformar em csv.

python3 cnpj.py ./dados1\ \(1\)/ csv /home/matheus/
Iniciando processamento em 2019-11-20 23:09:44.467879
Processando arquivo: ./dados1 (1)/
Traceback (most recent call last):
  File "cnpj.py", line 463, in <module>
    main()
  File "cnpj.py", line 455, in main
    cnpj_full(input_list, tipo_output, output_path)
  File "cnpj.py", line 220, in cnpj_full
    encoding='ISO-8859-15')
  File "/home/matheus/Downloads/FlareGet/Others/CNPJ-full-master/cfwf.py", line 49, in read_cfwf
    encoding=encoding)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 803, in read_fwf
    return _read(filepath_or_buffer, kwds)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1132, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 3605, in __init__
    PythonParser.__init__(self, f, **kwds)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2225, in __init__
    memory_map=self.memory_map)
  File "/home/matheus/anaconda3/lib/python3.7/site-packages/pandas/io/common.py", line 424, in _get_handle

**Comment by antonioanerao** [comment]
Esse repositório não recebe mais suporte? Estou com o mesmo erro e não consegui resolver =/

**Comment by antonioanerao** [comment]
Na verdade consegui rodar agora. Eu tinha esquecido do --dir :P

**Comment by fabioserpa** [comment]
Em relação a questão original, o comando utilizado não parece correto. O que seria o (1)?

**Comment by antonioanerao** [comment]
Opa. Desculpa a demora em responder. Para o comando funcionar eu fiz o seguinte:
1) Dentro da pasta do projeto CNPJ Full eu criei uma pasta chamada entrada e uma pasta chamada saída. Dentro da pasta entrada eu deixei todos os arquivos que eu baixei.

O comando eu usei: python3 cnpj.py entrada sqlite saida --dir

Se der problema no "panda" pode ser que você esteja usando mais de uma versão Python. Instale o panda manualmente para a versão do Python3

Para ubuntu/debian: sudo apt-get install python3-pandas

Para outras versões dê uma olhada na doc: https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html

**Comment by fabioserpa** [comment]
@BlackjackMT , conseguiu resolver?

**Comment by fabioserpa** [comment]
Fechando essa issue, uma vez que não houve manifestação posterior sobre continuidade do problema.
