### ISSUE TITLE
Erro ao transformar os arquivos zipados para SQLite

### ISSUE THREAD

**Issue by legalindo** [fabioserpa/CNPJ-full#30]
Pessoal, boa tarde

fiz o download dos arquivos zip e iniciei  transformação em SQLipe,
No aquivo DADOS_ABERTOS_CNPJ_11 deu o erro abaixo, não estou conseguindo arrumar, alguem poderia me ajudar?

C:\Users\lgalmeida\Desktop\CNPJ-full-master>cnpj.py arquivos_zipados sqlite BancodeDados --dir
Iniciando processamento em 2019-12-11 08:31:33.288620
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_01.zip
Bloco 1: até linha 200000. [Emps:0|Socios:0|CNAEs:0]
INFORMACOES DO HEADER:
Nome do arquivo: F.K032001K
Data de gravacao: 20191109
Numero da remessa: 00000001
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_02.zip:464741]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_03.zip:1011468]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_04.zip:1576118]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_05.zip:2097973]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_06.zip:2938221]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_07.zipEs:3768101]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_08.zipEs:4767635]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_09.zipEs:5876265]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_10.zipEs:6857512]
Processando arquivo: arquivos_zipados\DADOS_ABERTOS_CNPJ_11.zipEs:8006986]
Traceback (most recent call last):20228564|Socios:15969481|CNAEs:8439963]
  File "C:\Users\lgalmeida\Desktop\CNPJ-full-master\cnpj.py", line 463, in <module>
    main()
  File "C:\Users\lgalmeida\Desktop\CNPJ-full-master\cnpj.py", line 455, in main
    cnpj_full(input_list, tipo_output, output_path)
  File "C:\Users\lgalmeida\Desktop\CNPJ-full-master\cnpj.py", line 223, in cnpj_full
    for i_bloco, bloco in enumerate(dados):
  File "C:\Users\lgalmeida\Desktop\CNPJ-full-master\cfwf.py", line 107, in _cfwf_chunck_reader
    yield _cfwf_chunck(chunk, type_width, colspecs, names, dtype)
  File "C:\Users\lgalmeida\Desktop\CNPJ-full-master\cfwf.py", line 97, in _cfwf_chunck
    .astype(col_type))
  File "C:\Users\lgalmeida\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\generic.py", line 5691, in astype
    **kwargs)
  File "C:\Users\lgalmeida\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals\managers.py", line 531, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "C:\Users\lgalmeida\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals\managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\lgalmeida\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals\blocks.py", line 534, in astype
    **kwargs)
  File "C:\Users\lgalmeida\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals\blocks.py", line 633, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "C:\Users\lgalmeida\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\dtypes\cast.py", line 702, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float:

**Comment by iradojapa** [comment]
Olá, 

Parabéns pela ajuda.

Estou com um erro semelhante ao do @legalindo, tanto por arquivos ZIP ou após a descompactação chegando no arquivo 11 apresenta o erro abaixo:

X:\Users\XXX\Downloads\CNPJ_RFB\CNPJ-full-master> python cnpj.py X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db sqlite X:\Users\XXX\Downloads\CNPJ_RFB\db\sqlite --dir
Iniciando processamento em 2020-02-29 21:37:33.745852
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00001
Bloco 1: até linha 200000. [Emps:0|Socios:0|CNAEs:0]
INFORMACOES DO HEADER:
Nome do arquivo: F.K032001K
Data de gravacao: 20200125
Numero da remessa: 00000001
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00002
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00003
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00004
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00005
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00006
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00007
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00008
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00009
Processando arquivo: X:\Users\XXX\Downloads\CNPJ_RFB\RFB_db\K3241.K03200DV.D00124.L00010
Traceback (most recent call last):18211258|Socios:15135155|CNAEs:7298344]
  File "cnpj.py", line 463, in <module>
    main()
  File "cnpj.py", line 455, in main
    cnpj_full(input_list, tipo_output, output_path)
  File "cnpj.py", line 270, in cnpj_full
    df = df[df[CNA_CNAE] != '0000000']
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\frame.py", line 2791, in __getitem__
    return self._getitem_bool_array(key)
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\frame.py", line 2845, in _getitem_bool_array
    return self._take_with_is_copy(indexer, axis=0)
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 3409, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis, **kwargs)
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 3394, in take
    new_data = self._data.take(
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\internals\managers.py", line 1392, in take
    new_labels = self.axes[axis].take(indexer)
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\indexes\base.py", line 763, in take
    taken = self.values.take(indices)
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\indexes\base.py", line 3659, in values
    return self._data.view(np.ndarray)
  File "X:\Users\XXX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\indexes\range.py", line 165, in _data
    self._cached_data = np.arange(
MemoryError: Unable to allocate 41.4 MiB for an array with shape (5426190,) and data type int64

Alguma sugestão de correção?

**Comment by fabioserpa** [comment]
O problema persiste? Chegou a tentar com arquivos mais recentes baixados? Será que está faltando memória RAM para esse processamento? Talvez você precise baixar o tamanho do bloco de processamento.

**Comment by legalindo** [comment]
Com os novos arquivos não tentei ainda, irei fazer isso. Memória RAM acho
difícil,  pois estou usando uma máquina ótima, pode ser na conversão de
algum campo está dando erro,

Vou baixar os novos arquivos e tentar rodar

Leandro Galindo

**Comment by fabioserpa** [comment]
O problema foi resolvido baixando os arquivos mais recentes?

**Comment by cristovaor** [comment]
Também tive o mesmo problema ao realizar a conversão pra o SQLite, alguém mais teve esse erro? Os dados são os mais recentes de junho. 

Bloco 53: até linha 10600000. [Emps:0|Socios:0|CNAEs:0]
INFORMACOES DO HEADER:
Nome do arquivo: ELEICAO 200
Data de gravacao: 8 RONALD
Numero da remessa: O BATIST
Traceback (most recent call last):
  File "cnpj.py", line 463, in <module>
    main()
  File "cnpj.py", line 455, in main
    cnpj_full(input_list, tipo_output, output_path)
  File "cnpj.py", line 223, in cnpj_full
    for i_bloco, bloco in enumerate(dados):
  File "C:\Users\cristovao.costa\CNPJ\cfwf.py", line 107, in _cfwf_chunck_reader
    yield _cfwf_chunck(chunk, type_width, colspecs, names, dtype)
  File "C:\Users\cristovao.costa\CNPJ\cfwf.py", line 97, in _cfwf_chunck
    .astype(col_type))
  File "C:\Users\cristovao.costa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "C:\Users\cristovao.costa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\internals\managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "C:\Users\cristovao.costa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\cristovao.costa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\internals\blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "C:\Users\cristovao.costa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\internals\blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "C:\Users\cristovao.costa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\core\dtypes\cast.py", line 729, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float:

**Comment by fabioserpa** [comment]
Estranho, algum arquivo parece estar corrompido, pois em algum momento, ao ler uma linha no meio do processamento, ele encontrou uma com carácter inicial indicando linha de cabeçalho, o que deveria ocorrer apenas para a primeira linha de todas. Eu ainda não baixei os arquivos de junho. Qual arquivo estava sendo processado quando o erro ocorreu? Alguém já conseguiu processar os arquivos de junho com sucesso?

**Comment by rictom** [comment]
Eu consegui processar os arquivos da receita federal de julho e de setembro/2020 para o formato sqlite com sucesso. Gostaria de aproveitar para agradecer ao Fábio pelo ótimo script, poupando tempo e dor de cabeça pra abrir os arquivos da Receita Federal. Eu estou utilizando o CNPJ_full.db num projeto de visualização de dados [https://github.com/rictom/rede-cnpj](https://github.com/rictom/rede-cnpj). Pra quem precisar da tabela em sqlite já processada pelo script, coloquei no google drive pra baixar [https://drive.google.com/drive/folders/1Gkeq27aHv6UgT8m30fc4hZWMPqdhEHWr?usp=sharing](https://drive.google.com/drive/folders/1Gkeq27aHv6UgT8m30fc4hZWMPqdhEHWr?usp=sharing), referência 5/9/2020.

**Comment by fabioserpa** [comment]
Vou fechar essa issue uma vez que não houve manifestação posterior de continuidade do problema em novas tentativas de downloads.
